version: 1
backend:
  phases:
    build:
      commands:
        - npm ci
        - npm run build
frontend:
  phases:
    build:
      commands:
        - echo "No frontend build needed"
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
